INSERT INTO discount_configuration (
    id,
    code,
    type,
    enabled,
    percentage,
    start_at,
    end_at,
    minimum_orders,
    lookback_months,
    created_at,
    updated_at,
    updated_by
)
VALUES
    (
        '84b39f83-1c4f-49a8-9797-0c7cddbb0460',
        'TIME_RANGE',
        'TIME_RANGE',
        FALSE,
        10.00,
        NULL,
        NULL,
        NULL,
        NULL,
        NOW(),
        NOW(),
        NULL
    ),
    (
        'a2bd76ca-b2f4-44ee-8722-e011e425cc31',
        'RANDOM_ORDER',
        'RANDOM_ORDER',
        FALSE,
        50.00,
        NULL,
        NULL,
        NULL,
        NULL,
        NOW(),
        NOW(),
        NULL
    ),
    (
        'cf03dbec-d21c-4940-a6ad-507fb96721a2',
        'FREQUENT_CUSTOMER',
        'FREQUENT_CUSTOMER',
        FALSE,
        5.00,
        NULL,
        NULL,
        5,
        12,
        NOW(),
        NOW(),
        NULL
    );