package com.launchforge.audit.application;

public enum AuditAction {
    USER_CREATED,
    USER_STATUS_CHANGED,
    USER_ROLE_CHANGED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DISABLED,
    INVENTORY_ADJUSTED,
    ORDER_CREATED,
    ORDER_CONFIRMED,
    ORDER_COMPLETED,
    ORDER_CANCELLED,
    DISCOUNT_CONFIGURATION_UPDATED
}
